# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /projects/opt/centos8/x86_64/cmake/3.19.2/bin/cmake

# The command to remove a file.
RM = /projects/opt/centos8/x86_64/cmake/3.19.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /vast/home/stevenw/Fierro_Steven

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /vast/home/stevenw/Fierro_Steven

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/projects/opt/centos8/x86_64/cmake/3.19.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/projects/opt/centos8/x86_64/cmake/3.19.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /vast/home/stevenw/Fierro_Steven/CMakeFiles /vast/home/stevenw/Fierro_Steven//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /vast/home/stevenw/Fierro_Steven/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named distclean

# Build rule for target.
distclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 distclean
.PHONY : distclean

# fast build rule for target.
distclean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distclean.dir/build.make CMakeFiles/distclean.dir/build
.PHONY : distclean/fast

#=============================================================================
# Target rules for targets named elements

# Build rule for target.
elements: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 elements
.PHONY : elements

# fast build rule for target.
elements/fast:
	$(MAKE) $(MAKESILENT) -f Elements/elements/CMakeFiles/elements.dir/build.make Elements/elements/CMakeFiles/elements.dir/build
.PHONY : elements/fast

#=============================================================================
# Target rules for targets named swage

# Build rule for target.
swage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 swage
.PHONY : swage

# fast build rule for target.
swage/fast:
	$(MAKE) $(MAKESILENT) -f Elements/swage/CMakeFiles/swage.dir/build.make Elements/swage/CMakeFiles/swage.dir/build
.PHONY : swage/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) $(MAKESILENT) -f Elements/common/CMakeFiles/common.dir/build.make Elements/common/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named matar

# Build rule for target.
matar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 matar
.PHONY : matar

# fast build rule for target.
matar/fast:
	$(MAKE) $(MAKESILENT) -f Elements/matar/src/CMakeFiles/matar.dir/build.make Elements/matar/src/CMakeFiles/matar.dir/build
.PHONY : matar/fast

#=============================================================================
# Target rules for targets named geometry

# Build rule for target.
geometry: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 geometry
.PHONY : geometry

# fast build rule for target.
geometry/fast:
	$(MAKE) $(MAKESILENT) -f Elements/geometry/CMakeFiles/geometry.dir/build.make Elements/geometry/CMakeFiles/geometry.dir/build
.PHONY : geometry/fast

#=============================================================================
# Target rules for targets named slam

# Build rule for target.
slam: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 slam
.PHONY : slam

# fast build rule for target.
slam/fast:
	$(MAKE) $(MAKESILENT) -f Elements/slam/CMakeFiles/slam.dir/build.make Elements/slam/CMakeFiles/slam.dir/build
.PHONY : slam/fast

#=============================================================================
# Target rules for targets named test_bernstein_polynomials

# Build rule for target.
test_bernstein_polynomials: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bernstein_polynomials
.PHONY : test_bernstein_polynomials

# fast build rule for target.
test_bernstein_polynomials/fast:
	$(MAKE) $(MAKESILENT) -f Elements/tests/CMakeFiles/test_bernstein_polynomials.dir/build.make Elements/tests/CMakeFiles/test_bernstein_polynomials.dir/build
.PHONY : test_bernstein_polynomials/fast

#=============================================================================
# Target rules for targets named test_lagrange_polynomials

# Build rule for target.
test_lagrange_polynomials: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_lagrange_polynomials
.PHONY : test_lagrange_polynomials

# fast build rule for target.
test_lagrange_polynomials/fast:
	$(MAKE) $(MAKESILENT) -f Elements/tests/CMakeFiles/test_lagrange_polynomials.dir/build.make Elements/tests/CMakeFiles/test_lagrange_polynomials.dir/build
.PHONY : test_lagrange_polynomials/fast

#=============================================================================
# Target rules for targets named test_legendre_element

# Build rule for target.
test_legendre_element: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_legendre_element
.PHONY : test_legendre_element

# fast build rule for target.
test_legendre_element/fast:
	$(MAKE) $(MAKESILENT) -f Elements/tests/CMakeFiles/test_legendre_element.dir/build.make Elements/tests/CMakeFiles/test_legendre_element.dir/build
.PHONY : test_legendre_element/fast

#=============================================================================
# Target rules for targets named test_slam_math

# Build rule for target.
test_slam_math: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_slam_math
.PHONY : test_slam_math

# fast build rule for target.
test_slam_math/fast:
	$(MAKE) $(MAKESILENT) -f Elements/tests/CMakeFiles/test_slam_math.dir/build.make Elements/tests/CMakeFiles/test_slam_math.dir/build
.PHONY : test_slam_math/fast

#=============================================================================
# Target rules for targets named test_legendre_ref_integration

# Build rule for target.
test_legendre_ref_integration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_legendre_ref_integration
.PHONY : test_legendre_ref_integration

# fast build rule for target.
test_legendre_ref_integration/fast:
	$(MAKE) $(MAKESILENT) -f Elements/tests/CMakeFiles/test_legendre_ref_integration.dir/build.make Elements/tests/CMakeFiles/test_legendre_ref_integration.dir/build
.PHONY : test_legendre_ref_integration/fast

#=============================================================================
# Target rules for targets named test_lagrange_element

# Build rule for target.
test_lagrange_element: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_lagrange_element
.PHONY : test_lagrange_element

# fast build rule for target.
test_lagrange_element/fast:
	$(MAKE) $(MAKESILENT) -f Elements/tests/CMakeFiles/test_lagrange_element.dir/build.make Elements/tests/CMakeFiles/test_lagrange_element.dir/build
.PHONY : test_lagrange_element/fast

#=============================================================================
# Target rules for targets named test_legendre_polynomials

# Build rule for target.
test_legendre_polynomials: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_legendre_polynomials
.PHONY : test_legendre_polynomials

# fast build rule for target.
test_legendre_polynomials/fast:
	$(MAKE) $(MAKESILENT) -f Elements/tests/CMakeFiles/test_legendre_polynomials.dir/build.make Elements/tests/CMakeFiles/test_legendre_polynomials.dir/build
.PHONY : test_legendre_polynomials/fast

#=============================================================================
# Target rules for targets named Meshbox

# Build rule for target.
Meshbox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Meshbox
.PHONY : Meshbox

# fast build rule for target.
Meshbox/fast:
	$(MAKE) $(MAKESILENT) -f Elements/mesh_tools/box_mesh_creator/CMakeFiles/Meshbox.dir/build.make Elements/mesh_tools/box_mesh_creator/CMakeFiles/Meshbox.dir/build
.PHONY : Meshbox/fast

#=============================================================================
# Target rules for targets named Hydro

# Build rule for target.
Hydro: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Hydro
.PHONY : Hydro

# fast build rule for target.
Hydro/fast:
	$(MAKE) $(MAKESILENT) -f Explicit-Lagrange/src/CMakeFiles/Hydro.dir/build.make Explicit-Lagrange/src/CMakeFiles/Hydro.dir/build
.PHONY : Hydro/fast

#=============================================================================
# Target rules for targets named fierro

# Build rule for target.
fierro: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fierro
.PHONY : fierro

# fast build rule for target.
fierro/fast:
	$(MAKE) $(MAKESILENT) -f Explicit-Lagrange/test/CMakeFiles/fierro.dir/build.make Explicit-Lagrange/test/CMakeFiles/fierro.dir/build
.PHONY : fierro/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... distclean"
	@echo "... Hydro"
	@echo "... Meshbox"
	@echo "... common"
	@echo "... elements"
	@echo "... fierro"
	@echo "... geometry"
	@echo "... matar"
	@echo "... slam"
	@echo "... swage"
	@echo "... test_bernstein_polynomials"
	@echo "... test_lagrange_element"
	@echo "... test_lagrange_polynomials"
	@echo "... test_legendre_element"
	@echo "... test_legendre_polynomials"
	@echo "... test_legendre_ref_integration"
	@echo "... test_slam_math"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

